### ISSUE TITLE
wrong checksum on darwin arm64 for 0.26.0

### ISSUE THREAD

**Issue by transacid** [upbound/homebrew-tap#51]
the formular for up 0.26.0 fails at least for `darwin` `arm64` with a checksum error
```
==> Fetching upbound/tap/up
==> Downloading https://cli.upbound.io/stable/v0.26.0/bundle/up/darwin_arm64.tar.gz
######################################################################################################################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 1a33651f3cdd6c743054bc528cf6c78a538f0bdb9a01d3a96587d1d9880c5032
  Actual: f44620e2d350ee03cbf131c922e6355b992a12f8cbe7f819ff37dcbc5e765637
    File: /Users/boris.petersen/Library/Caches/Homebrew/downloads/66854dc0dc8a866612ad64e18c2683036b45bba462027866cbf7a02810cdf304--darwin_arm64.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by danielloader** [comment]
As a temporary workaround to keep being able to do brew upgrade:

`brew pin upbound/tap/up`

Remember to unpin it later once this is fixed.

**Comment by jayonthenet** [comment]
Problem was fixed by @jastang - this issue could be closed

**Comment by cychiang** [comment]
Hi @jastang @jayonthenet issue still there. 

The checksum for all files in `docker-credential-up` are incorrect. 

I have checked into the [url](https://cli.upbound.io/stable/v0.26.0/?prefix=stable/v0.26.0/bundle/docker-credential-up/) for artifacts and here are the correct list: 

```bash
c06493633c1089ea3804acf9717ef0f1a6dc6d8ddb10e496a99fde80407fc070  darwin_arm64.tar.gz
9d19c4c5ffe3192b5e46a3a865fb2ade477d8d3d41361e5a3a88b2e61d6f0f6c  darwin_amd64.tar.gz
7425e0398e779cee0b9c98914473eb0392dacd151b4582a8ceb063e751aee801  linux_amd64.tar.gz
b856a86e531c8d17247f6499727a490e6e9698f5902a10a0baeac9eb8bbec820  linux_arm.tar.gz
9c0b943ed4fb346c9e83ea87536309ebbff651638f6db114c55ac3825235961d  linux_arm64.tar.gz
f8eade4b63eb2171ca8ca3208cbaff083661409c16764f1fe092732c3d8731f0  windows_amd64.tar.gz
```

**Comment by jastang** [comment]
@cychiang thanks, looks like there was an issue with the automation. I'm going to revert the previous commits in #50 and re-generate the checksums.

**Comment by cychiang** [comment]
ah, okay then I can close my PR.

**Comment by jastang** [comment]
@cychiang @transacid #55 regenerated the checksums and should resolve all mismatches now. thanks for your patience.

**Comment by cychiang** [comment]
@jastang thanks, it works on my end(mac)

**Comment by transacid** [comment]
lgtm, thanks!
